import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"



// This file defines the root layout for the app, which is used for both SSR and RSC.


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const momo = localFont({
  src: "/fonts/MomoTrustDisplay-Regular.ttf",
  variable: "--font-momo"
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${momo.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
